### ISSUE TITLE
reading the same values

### ISSUE THREAD

**Issue by Nikitok122** [MickTheMechanic/arduino_sw6115#1]
hello!!! just connected to my power bank and reading the same values all the time
Battery voltage: 4.91400 V
Output voltage: 16.38000 V
Charging current: 14.62500 A
Discharge current: 14.62500 A
IC temperature: 329.03226 °C
NTC voltage: 4.50450 V

**Comment by MickTheMechanic** [comment]
Hi, you have closed the issue, so I am not sure if you are still having this issue.

these are the default values that show if there is a connection issue.

Did you connect some pull-up resistors to the SDA and SCL lines?
